-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2018-11-29 14:19

CREATE TABLE IF NOT EXISTS driver_misses_customer (
    "customer.id"        CHAR(36)         ENCODE LZO NOT NULL,
    "customer.is_vip"    BOOLEAN          ENCODE RAW NOT NULL,
    "employee.id"        CHAR(36)         ENCODE LZO NOT NULL,
    "employee.job_role"  VARCHAR(10)      ENCODE LZO NOT NULL,
    "event"              CHAR(22)         ENCODE LZO NOT NULL,
    "location.elevation" SMALLINT         ENCODE LZO NOT NULL,
    "location.latitude"  DOUBLE PRECISION ENCODE RAW NOT NULL,
    "location.longitude" DOUBLE PRECISION ENCODE RAW NOT NULL,
    "package.id"         CHAR(36)         ENCODE LZO NOT NULL,
    "timestamp"          TIMESTAMP        ENCODE LZO NOT NULL
);

COMMENT ON TABLE driver_misses_customer IS 'Source: driver_misses_customer.json';
