-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.3.1
-- Generated: 2018-11-29 14:19

CREATE TABLE IF NOT EXISTS mechanic_changes_oil (
    "employee.id"       CHAR(36)    ENCODE LZO NOT NULL,
    "employee.job_role" VARCHAR(12) ENCODE LZO NOT NULL,
    "event"             CHAR(20)    ENCODE LZO NOT NULL,
    "timestamp"         TIMESTAMP   ENCODE LZO NOT NULL,
    "vehicle.mileage"   INT         ENCODE LZO NOT NULL,
    "vehicle.vin"       CHAR(17)    ENCODE LZO NOT NULL
);

COMMENT ON TABLE mechanic_changes_oil IS 'Source: mechanic_changes_oil.json';
